#  yml和properties同时存在时，以properties为主。YAML一定要按格式来存放，否则会出现难以发现的问题，这点比较坑，使用时要注意
#YAML是json的超集，提供了方便的格式用于层次化配置数据。
#YAML语法格式：
#标准格式：key:(空格)value，使用空格代表层级关系，以“：”结束

# 端口设置
server:
  port: 80
  servlet:
    context-path: /dev

# 是否输出debug信息
debug: false

spring:

  http:
    encoding:
      charset: UTF-8

  # 静态文件请求匹配方式
  mvc:
    static-path-pattern: /**

  #thymelea模板配置
  thymeleaf:
    enabled: true
    servlet:
      content-type: text/html
    prefix: classpath:/templates/   # 访问templates下的html文件需要配置模板，映射
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #热部署文件，页面不产生缓存，及时更新,不然没法看到实时页面
    cache: false
    #是否在呈现模板之前检查模板是否存在
    check-template: true
    #检查模板位置是否正确(默认值:true)
    check-template-location: true

  #声明thymeleaf使用非严格的html。
  #    check-template: true
  #    check-template-location: true
  #    mode: LEGACYHTML5

  #  #不扫描thymelea模板文件
  #  freemarker:
  #    checkTemplateLocation: false

  # mysql 数据库连接参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

  #  jpa配置
  # ddl-auto参数说明
  #   1、create:每次都删除并新建数据库，数据不被保存。使用create可以根据model创建数据库表。
  #   2、update:可以自动创建表，每次运行数据不会更新。如果表结构改变，不会删除原来的行，而是新增一列。
  #   3、validate：验证表结构和插入数据，不会创建新表。如果校验不通过，将启动失败。
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true      #打印sql语句
    #open-in-view会注册一个OpenEntityManagerInViewInterceptor。在处理请求时，将 EntityManager 绑定到整个处理流程中（model->dao->service->controller），
    #开启和关闭session。这样一来，就不会出现 no Session 的错误了（可以尝试将该配置的值置为 false, 就会出现懒加载的错误了。）
    open-in-view: false

# 指定mapper文件路径 , 配置包中类别名
mybatis:
  #  mapper层要想被正确装配，需要在mapper层接口上添加@Mapper注解或者在启动上添加@MapperScan注解完成扫描
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hzero.demo.springboot.pojo

# 指定日志打印级别，输出SQL语句
#showSql
logging:
  level:
    com:
      example:
        mapper : debug

